#!/bin/bash

# load colors and fonts
source "$HOME"/.config/i3blocks/functions && load_style

# load mouse-click actions
if [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
    alacritty -e htop --sort-key PERCENT_CPU
fi

# get required values
cpu_load=$(cut -d' ' -f1 /proc/loadavg)

# get status
get_status_color() {
    local warning="$1"
    local critical="$2"
    if [ cpu_load -ge "$critical" ]; then
        echo "$color_nok"     # nok
    elif [ cpu_load -ge "$warning" ]; then
        echo "$color_warn"    # warn
    else
        echo "$color_ok"      # ok
fi
}

# main function
i3blocks_check() {
    local warning="$1"
    local critical="$2"
    local status_color=$(get_status_color "$warning" "$critical")
    printf "%s\n" "<span font='$font_text'>$cpu_load </span><span font='$font_glyphs' color='$status_color'></span>"
}
