#!/bin/bash

# load colors and fonts
source "$HOME"/.config/i3blocks/functions && load_style

# get wireless interface name
if [ -n "${BLOCK_INSTANCE:-}" ]; then
	int="${BLOCK_INSTANCE}"
else
	int="$(tail -1 /proc/net/wireless | awk '{print $1}' | sed 's/://g')"
fi

# load mouse-click actions
if [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
    "$HOME"/.config/scripts/tools/connect-wifi.sh
fi

# get required values
wifi_signal=$(awk -v interface="$int" -F'[: ]+' '$0 ~ interface {sub(/\.$/, "", $3); print $3}' /proc/net/wireless)

# get status
get_status_color() {
    local warning="$1"
    local critical="$2"
    if [ "$wifi_signal" -le "$critical" ]; then
        echo $color_nok     # nok
    elif [ "$wifi_signal" -le "$warning" ]; then
        echo $color_warn    # warn
    else
        echo $color_ok      # ok
    fi
}

# main function
i3blocks_check() {
    local warning="$1"
    local critical="$2"
    local status_color=$(get_status_color "$warning" "$critical")
    printf "%s\n" "<span font='$font_text'>$wifi_signal% </span><span font='$font_glyphs' color='$status_color'></span>"
}
